apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 80
          targetPort: 80
          protocol: TCP
      healthChecks: []
      name: test1-main
      imagePullPolicy: Always
      imageRegistry: docker.io//test1
      imagePullSecretName: imagepull-docker
      credentialId: credential_5ce13913-baf9-44e9-b81b-39b3f92bcaa6
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: test1
    version: v1.0.0
    applicationId: app_b63d3aa8-8fa9-4867-a1a9-001d1e8fd76e
    projectId: project_6fa544f1-ae5e-4fbd-b7b9-85cc84824c03
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_bedd0302-7906-46b1-8285-e7c38f5f1335
    environmentName: staging
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: test1
  serviceType: ClusterIP
  version: v1.0.0
  namespace: skyu-ui-automation-staging
