apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: test2-v1-0-0
  labels:
    app: test2-v1-0-0
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_6fa544f1-ae5e-4fbd-b7b9-85cc84824c03
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test2-v1-0-0
