apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: januda-setup-test-v1-0-0
  labels:
    app: januda-setup-test-v1-0-0
    applicationId: app_340dfe80-ce6a-41df-ab42-cbb73a3f8439
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_d2301adc-5288-4026-aaad-fcb3e1d34293
    environmentId: env_5416bc69-ed2e-46e7-9a62-8f34e65bdcf4
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: januda-setup-test-v1-0-0
