apiVersion: apps/v1
kind: Deployment
metadata:
  name: januda-setup-test-v1-0-0
  labels:
    app: januda-setup-test-v1-0-0
    applicationId: app_340dfe80-ce6a-41df-ab42-cbb73a3f8439
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_d2301adc-5288-4026-aaad-fcb3e1d34293
    environmentId: env_dc884329-aad6-489b-bc0b-b26ff4bf3afd
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app: januda-setup-test-v1-0-0
  template:
    metadata:
      labels:
        app: januda-setup-test-v1-0-0
        applicationId: app_340dfe80-ce6a-41df-ab42-cbb73a3f8439
        version: v1.0.0
        organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
        projectId: project_d2301adc-5288-4026-aaad-fcb3e1d34293
        environmentId: env_dc884329-aad6-489b-bc0b-b26ff4bf3afd
